# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdcefc56ce2289f07639e24382b65ba5e389e61f67d84e19bbc0b02fe020f836b86f16a8f8b24da34dde3026edd10005f85cf23e5d0d6a3823e3babfe96e8207

test:
  secret_key_base: 10f29ede4222098763a5b06c518840bb1b19a9f85ec1fa3cbc18f3e30bccc7ab9f9d715a347dc1c1bd77a5d6567b964583cd99176c94d4f88f5f75e10baa23da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
